### ISSUE TITLE
npm WARN ssh-proxy@1.0.0 No repository field. 

### ISSUE THREAD

**Issue by UUDey** [dzt/easy-proxy#1]
npm WARN ssh-proxy@1.0.0 No repository field.
Is this meant to happen?
Also wont let me retrieve sshkeyid:
node scripts/ssh_keys
{ id: 'unauthorized', message: 'Unable to authenticate you.' }

**Comment by dzt** [comment]
Just ignore it, it’s nothing important.

**Comment by dzt** [comment]
[bbc58b6](https://github.com/dzt/easy-proxy/commit/8c3cf06c6847c8b01d1806d04c4078591167b955)

**Comment by dzt** [comment]
[bbc58b6](https://github.com/dzt/easy-proxy/commit/8c3cf06c6847c8b01d1806d04c4078591167b955)

**Comment by UUDey** [comment]
bbc58b6??
