### ISSUE TITLE
still returning error on keyid

### ISSUE THREAD

**Issue by UUDey** [dzt/easy-proxy#2]
{ id: 'unauthorized', message: 'Unable to authenticate you.' }
undefined

**Comment by lfcameron7** [comment]
@UUDey how did you fix this?

**Comment by dzt** [comment]
@lfcameron7 use the proper DigitalOcean API Key

**Comment by UUDey** [comment]
@lfcameron7 On security it says SSH KEYS, copy and paste the "Fingerprint"

**Comment by lfcameron7** [comment]
@UUDey @dzt ahhh, thank you :)

**Comment by lfcameron7** [comment]
@UUDey but what do I do with it?

**Comment by UUDey** [comment]
@lfcameron7 put it in KeyId in the config
